version: '3.9'

services:

  proxy:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./test_frontend/:/test_frontend
    restart: always
    ports:
     - 8908:8908

  game_server:
    build: .
    ports:
      - "8909:8072"
    environment:
      - postgres_host=db
      - postgres_port=5432
      - cent_url=http://centrifugo:8000
    command: "python main.py --mode 1"
    restart: always
    depends_on:
      - db
      - centrifugo
      - game_updates

  game_updates:
    build: .
    environment:
      - postgres_host=db
      - postgres_port=5432
      - cent_url=http://centrifugo:8000
    command: "python main.py --mode 0"
    restart: always
    depends_on:
      - db
      - centrifugo

  centrifugo:
    image: centrifugo/centrifugo
    restart: always
    ports:
      - "8910:8000"
    volumes:
      - ./config.json:/centrifugo/config.json

  db:
    image: postgres:16.2-bullseye
    ports:
      - "8911:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app