version: '3.9'

services:
  centrifugo:
    image: centrifugo/centrifugo
    ports:
      - "8910:8000"
    volumes:
      - ./config.json:/centrifugo/config.json

  db:
    image: postgres:16.2-bullseye
    ports:
      - "8911:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app